name: simple_flutter_mvvm
description: simple MVVM app using GetX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  freezed_annotation: ^1.1.0
  shimmer: ^2.0.0
  json_annotation: ^4.3.0
  intl: ^0.17.0
  mockito: ^5.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.0.0


flutter:
  uses-material-design: true